### ISSUE TITLE
Cannot start docker image on arm-based Mac

### ISSUE THREAD

**Issue by torleifs** [ZeldaIV/AuthServer#30]
Following the instructions in the READMEs and doing 
`docker-compose up ` gives the following error:
seqsink_1  | Failed to create CoreCLR, HRESULT: 0x8007FF06
seqsink_1  | Failed to create CoreCLR, HRESULT: 0x8007FF06

And eventually:

```
docker_seqsink_1 exited with code 137
web_1      | [17:02:07 ERR] Could not initialize identity db after 5 attempts
web_1      | [17:02:07 WRN] Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
web_1      | [17:02:07 INF] User profile is available. Using '/root/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
web_1      | [17:02:07 INF] Entity Framework Core 5.0.3 initialized 'ApplicationDbContext' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: MaxPoolSize=128 ServerVersion 10.3.9-mariadb
web_1      | [17:02:07 ERR] An error occurred using the connection to database 'PowerDb' on server 'localhost'.
web_1      | [17:02:07 INF] A transient exception occurred during execution. The operation will be retried after 0ms.
web_1      | MySqlConnector.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
web_1      |    at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, Int32 startTickCount, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 381
web_1      |    at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 110
web_1      |    at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 140
web_1      |    at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 846
web_1      |    at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 410
web_1      |    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
web_1      |    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
web_1      |    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
web_1      |    at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
web_1      |    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
web_1      |    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
web_1      |    at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)

```

Error 137 indicates a SIGKIll or out of memory conditions so I also tried to increase  the memory for docker to 4GBs and swap space to 2GB

I found this issue 
https://github.com/datalust/seq-tickets/issues/1224
but I don't know if that is related.

My computer is:
MacBook Air (M1, 2020) with 8Gbs of memory.

**Comment by ZeldaIV** [comment]
I have updated the startup to only include app Development and local app settings only when these environments are specifically specified. It should work now.

**Comment by torleifs** [comment]
Thanks, but that didn't solve my problem. It is the startup of `docker_seqsink_1` and `docker_db_1` that fails. That happens before the app is started with `> dotnet AuthServer.dll`

**Comment by torleifs** [comment]
I was able to get mariadb to not fail on startup by upgrading it to the latest version. 
datalust/seq container still fails.

**Comment by ZeldaIV** [comment]
Okay, that one is not critical, so we can exclude it, or find a replacement. Does all fail when that one fails?

**Comment by torleifs** [comment]
Yes, everything fails because of this I think.
One more thing: upgrading to mariadb caused another error that is related to the upgrade. I think it said that we needed to use a Varchar instead of a char(14) for some table.
I can try to get a more specific description of this problem later today.

**Comment by torleifs** [comment]
This is the error I got from mariadb startup:
```
db_1       | 2021-08-20  8:52:18 0 [ERROR] Incorrect definition of table mysql.event: expected column 'definer' at position 3 to have type varchar(, found type char(141).
db_1       | 2021-08-20  8:52:18 0 [ERROR] mysqld: Event Scheduler: An error occurred when initializing system tables. Disabling the Event Scheduler.
```

**Comment by torleifs** [comment]
It was also necessary to upgrade the version used in  in `ConfigureServices`:

`var dbServerVersion = new MariaDbServerVersion(new Version(10, 6, 4));`
